# Generated by Django 4.2.10 on 2024-04-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cart_cartitem_remove_ordercartitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
